### ISSUE TITLE
Repository: Create `GenreRepository`

### ISSUE THREAD

**Issue by SardorSohinazarov** [SardorSohinazarov/AsilMedia#3]

**Comment by ibrohim-qosimov** [comment]
men zerikkanda eng onsonini yozib qpydim sekin merge qilish kerak ustoz

**Comment by QosimovIbrohim** [comment]
![image](https://github.com/SardorSohinazarov/AsilMedia/assets/128721965/0f6f8c14-b77f-4a5f-bcb4-127e96b5fc69)

**Comment by SardorSohinazarov** [comment]
> men zerikkanda eng onsonini yozib qpydim sekin merge qilish kerak ustoz

endi shuni refactor qilib bering teamlead
